# Generated by Django 5.0.1 on 2024-02-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tinetuser',
            name='bio',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
