# Generated by Django 5.0.1 on 2024-02-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_tinetuser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='tinetuser',
            name='calc_key',
            field=models.CharField(max_length=51, null=True),
        ),
    ]
