# Generated by Django 5.0.1 on 2024-02-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auditentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='tinetuser',
            name='api_key',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
