# Generated by Django 5.0.2 on 2024-02-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_sessiontoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiontoken',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
