# Generated by Django 5.0.2 on 2024-02-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_sessiontoken_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiontoken',
            name='token',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
