# Generated by Django 5.0.2 on 2024-03-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_appapikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appapikey',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appapikey',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
