# Generated by Django 5.0.2 on 2024-03-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_appapikey_user_alter_sessiontoken_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('database_name', models.CharField(max_length=18, unique=True)),
                ('fqdn', models.CharField(default='tinetuserdb.tkbstudios.com', max_length=255)),
                ('port', models.PositiveIntegerField(default=3306)),
            ],
        ),
    ]
