# Generated by Django 5.0.2 on 2024-03-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_userdb_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdb',
            name='password',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
