# Generated by Django 5.0.2 on 2024-03-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_userdb_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdb',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userdb',
            name='password',
        ),
        migrations.AddField(
            model_name='userdb',
            name='db_password',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
