# Generated by Django 5.0.2 on 2024-03-05 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_userdb_name_remove_userdb_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDB',
        ),
    ]
