# Generated by Django 5.0.2 on 2024-03-06 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_userdb_password_userdb_database_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdb',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
