# Generated by Django 5.0.2 on 2024-03-09 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_webpopup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webpopup',
            name='confirmed',
        ),
        migrations.RemoveField(
            model_name='webpopup',
            name='user',
        ),
        migrations.CreateModel(
            name='UserWebPopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False)),
                ('popup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.webpopup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='webpopup',
            name='users',
            field=models.ManyToManyField(related_name='webpopups', through='users.UserWebPopUp', to=settings.AUTH_USER_MODEL),
        ),
    ]
