# Generated by Django 5.0.2 on 2024-03-11 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_remove_webpopup_confirmed_remove_webpopup_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedApp',
            fields=[
                ('allow_id', models.AutoField(primary_key=True, serialize=False)),
                ('app_id', models.IntegerField(default=-1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
