# Generated by Django 5.0.2 on 2024-03-11 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_allowedapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allowedapp',
            name='app_id',
        ),
        migrations.AddField(
            model_name='allowedapp',
            name='app',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.appapikey'),
        ),
    ]
