# Generated by Django 5.0.2 on 2024-03-11 12:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_remove_allowedapp_app_id_allowedapp_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowedapp',
            name='granted_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
