# Generated by Django 5.0.2 on 2024-03-11 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_allowedapp_granted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowedapp',
            name='app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.appapikey'),
        ),
        migrations.AlterField(
            model_name='allowedapp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='allowedapp',
            unique_together={('user', 'app')},
        ),
    ]
