# Generated by Django 5.0.2 on 2024-03-12 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_allowedapp_app_alter_allowedapp_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedAppAuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('username', models.CharField(max_length=256, null=True)),
                ('allowed_app', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.allowedapp')),
            ],
        ),
    ]
