# Generated by Django 5.0.2 on 2024-03-15 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_allowedappauditentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDB',
        ),
    ]
