version: "3"
services:
  tinetdb:
    image: postgres:16-alpine
    hostname: tinetdb
    container_name: tinetdb
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - /home/ubuntu/tinetbackend/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=$DB_PASS
      - POSTGRES_USER=$DB_USER
      - POSTGRES_DB=$DB_NAME

  tinetredis:
    image: redis:latest
    container_name: tinetredis
    hostname: tinetredis
    restart: unless-stopped
    command: redis-server /data/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - ~/apps/redis:/data

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"

  tinetswagger:
    container_name: tinetswagger
    ports:
        - "8003:8080"
    environment:
        - BASE_URL=/swagger
        - SWAGGER_JSON_URL=https://raw.githubusercontent.com/tkbstudios/tinetswagger/main/v1.json
    image: swaggerapi/swagger-ui
    restart: unless-stopped
