# Generated by Django 5.0.2 on 2024-03-12 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0001_initial'),
        ('users', '0028_allowedappauditentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.appapikey'),
        ),
    ]
